{% set version = "0.18.0" %}

package:
  name: meson-python
  version: {{ version }}

source:
  url: https://github.com/mesonbuild/meson-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6435a1e3f59f3e40579659aa3e5866034c2072ad38060bd4cfec93a5f2471b02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - meson >=1.2.3
    - ninja
    - packaging >=23.2
    - pyproject-metadata >=0.9.0
    - pip
    - python {{ python_min }}
    - tomli >=1.0.0
  run:
    - meson >=1.2.3
    - ninja
    - packaging >=23.2
    - pyproject-metadata >=0.9.0
    - python >={{ python_min }}
    - tomli >=1.0.0

test:
  imports:
    - mesonpy
  commands:
    - pip check
    # CPPFLAGS exports -DNDEBUG which is unwanted
    - export CPPFLAGS=${CPPFLAGS//-DNDEBUG/}
    - pytest tests -vv
  source_files:
    - tests/
    - docs/
    - pyproject.toml
  requires:
    - {{ compiler('c') }}
    - cython
    - git
    - gitpython
    - patchelf  # [linux]
    - pip
    - pytest
    - pytest-mock
    - wheel
    - python {{ python_min }}

about:
  home: https://github.com/mesonbuild/meson-python
  doc_url: https://meson-python.readthedocs.io/en/latest/
  summary: Meson Python build backend (PEP 517)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
